USE aduedmapping_db;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS canvases (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  width DOUBLE NOT NULL DEFAULT 170,
  height DOUBLE NOT NULL DEFAULT 220,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS nodes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  device_id VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  location VARCHAR(255) NULL,
  x DOUBLE NULL,
  y DOUBLE NULL,
  coverage_radius DOUBLE NOT NULL DEFAULT 15.0,
  point_size DOUBLE NOT NULL DEFAULT 6,
  canvas_id INT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_nodes_canvas FOREIGN KEY (canvas_id) REFERENCES canvases(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS readings (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  node_id INT NOT NULL,
  ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  battery_pct INT NULL,
  battery_v DOUBLE NULL,

  temperature_c DOUBLE NULL,
  humidity_pct DOUBLE NULL,
  pressure_hpa DOUBLE NULL,

  eco2_ppm INT NULL,
  tvoc_ppb INT NULL,
  pm25_ugm3 DOUBLE NULL,

  raw_json JSON NULL,

  INDEX idx_node_ts (node_id, ts),
  CONSTRAINT fk_readings_node FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS walls (
  id INT AUTO_INCREMENT PRIMARY KEY,
  canvas_id INT NOT NULL DEFAULT 1,
  x1 DOUBLE NOT NULL,
  y1 DOUBLE NOT NULL,
  x2 DOUBLE NOT NULL,
  y2 DOUBLE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_walls_canvas FOREIGN KEY (canvas_id) REFERENCES canvases(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS canvas_elements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  canvas_id INT NOT NULL,
  type VARCHAR(32) NOT NULL,
  x DOUBLE NOT NULL,
  y DOUBLE NOT NULL,
  width DOUBLE NULL,
  height DOUBLE NULL,
  radius DOUBLE NULL,
  points JSON NULL,
  text VARCHAR(512) NULL,
  icon VARCHAR(64) NULL,
  fill_color VARCHAR(32) NULL DEFAULT '#3b82f6',
  stroke_color VARCHAR(32) NULL DEFAULT '#1e3a5f',
  stroke_width DOUBLE DEFAULT 2,
  font_size DOUBLE DEFAULT 14,
  rotation DOUBLE DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_elements_canvas FOREIGN KEY (canvas_id) REFERENCES canvases(id) ON DELETE CASCADE
);
